#!/bin/sh
if [ $# -lt 1 ]
then
	echo "Usage: `basename $0` <kernel config file>"
	exit 1
fi
config=$1
for i in `cat <<CONFIG
CONFIG_WLAN=y
CONFIG_WIRELESS=y
CONFIG_WIRELESS_EXT=y
CONFIG_WL12XX_PLATFORM_DATA=y
CONFIG_KEYS=y
CONFIG_SECURITY=y
CONFIG_CRYPTO=y
CONFIG_WIRELESS_EXT=y
CONFIG_CRYPTO_ARC4=y
CONFIG_CRYPTO_ECB=y
CONFIG_CRYPTO_AES=y
CONFIG_CRYPTO_MICHAEL_MIC=y
CONFIG_RFKILL=y
CONFIG_REGULATOR_FIXED_VOLTAGE=y
CONFIG_CRC7=y
CONFIG_NETFILTER=y
CONFIG_NETFILTER_ADVANCED=y
CONFIG_NF_CONNTRACK=y
CONFIG_NETFILTER_XTABLES=y
CONFIG_NF_DEFRAG_IPV4=y
CONFIG_NF_CONNTRACK_IPV4=y
CONFIG_NF_CONNTRACK_PROC_COMPAT=y
CONFIG_IP_NF_IPTABLES=y
CONFIG_IP_NF_FILTER=y
CONFIG_IP_NF_TARGET_LOG=y
CONFIG_NF_NAT=y
CONFIG_NF_NAT_NEEDED=y
CONFIG_IP_NF_TARGET_MASQUERADE=y
CONFIG_INPUT_UINPUT=y
CONFIG_NET_SCHED=y
CONFIG_NET_SCH_FIFO=y
CONFIG_TI_ST=y
CONFIG_BRIDGE_NETFILTER=y
CONFIG_STP=y                         
CONFIG_BRIDGE=y                      
CONFIG_BRIDGE_IGMP_SNOOPING=y
CONFIG_LLC=y 
CONFIG_HAS_IOMEM=y                   
CONFIG_HAS_IOPORT=y                  
CONFIG_HAS_DMA=y                     
CONFIG_NLATTR=y                      
CONFIG_AVERAGE=y
CONTIG_TI_ST=y

CONFIG
`; do
echo -n "Option $i: " 
grep -q "$i" ${config}
found=$?
[ $found -eq 0 ] && echo "is already set, do nothing" && continue 
echo "is not found, update config" 
echo "$i" >> ${config}
done
